const errors = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RACKS_OUT_OF_BOUND: "RACKS_OUT_OF_BOUND",
  DATA_NOT_FOUND: "DATA_NOT_FOUND",
  WAREHOUSE_NOT_INIT: "WAREHOUSE_NOT_INIT",
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
};

module.exports = {
  ...errors,
};
